### ISSUE TITLE
To be able to schedule clusterized tasks and non-clusterized timers

### ISSUE THREAD

**Issue by vondacho** [hendisantika/quarkus-quartz#1]
Given [this fact](https://quarkus.io/guides/scheduler-reference):

> If you add the quarkus-quartz dependency to your project the lightweight scheduler implementation from the quarkus-scheduler extension is automatically disabled.

With a clustered setup of Quartz in a multi-pods environment, it is no more possible to schedule local timers or local recurrent tasks in a given pod in order to trigger actions on some beans, using the `@Scheduled` annotation.

Does currently exist a recipe to mixt both needs in an elegant way? Or, is it possible to plan some development on the Quarkus-Quartz extension?

Best regards.

**Comment by hendisantika** [comment]
Can You send me PR for this @vondacho

**Comment by vondacho** [comment]
@hendisantika 
 I moved the issue to [https://github.com/quarkusio/quarkus/issues/41954](https://github.com/quarkusio/quarkus/issues/41954). I  propose to close the current one. Regards.
